apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  labels:
    app: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: client
        imagePullPolicy: Never
        env:
          - name: DISPLAY
            value: "10.31.151.4:0"
        command: ["bash"]
        args: ["launch_client.sh", "server-service"]