apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-client
  labels:
    app: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-client
  template:
    metadata:
      labels:
        app: demo-client
    spec:
      containers:
      - name: client
        image: client
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
